kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: example-task
  namespace: tekton-trusted-resources
spec:
  steps:
    - image: ubuntu
      name: echo
      command:
        - echo
      args:
        - "Hello World"
